# Generated by Django 2.1.2 on 2018-10-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Введите токен бота', max_length=100)),
                ('cosplay_ch', models.CharField(help_text='Введите id канала для постинга косплей-фото', max_length=100)),
                ('eso_news_ch', models.CharField(help_text='Введите id канала для новостей по ESO', max_length=100)),
                ('eso_status_ch', models.CharField(help_text='Введите id канала для статуса ESO-серверов', max_length=100)),
                ('eso_status_msg', models.CharField(help_text='Введите id заглавного-сообщения для статуса ESO-серверов', max_length=100)),
                ('delay', models.IntegerField(default=900)),
            ],
        ),
    ]
